M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-03-15T11:29:54-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-15T11:29:54-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X93.0Y-72.0
X93.0Y-123.5
X173.0Y-72.0
X173.0Y-123.5
M30
